name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{ secrets.GIT_CREDENTIALS }}

      - name: Git setup
        run: |
          git config --global user.email "meap@cin.ufpe.br"
          git config --global user.name "Mateus Elias"

      - name: Git fetch
        run: |
          git fetch --all
          git branch -a

      - name: Build & Deploy
        run: |
          npm install
          npm run predeploy
          npm run deploy