name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build & Deploy
        run: |
          git config --global user.name "mateuseap" 
          git config --global user.email "meap@cin.ufpe.br" 
          npm install
          npm run predeploy
          npm run deploy